### ISSUE TITLE
Flash icon is not showing

### ISSUE THREAD

**Issue by rickmrobin** [AmolGangadhare/flutter_barcode_scanner#97] opened 2020-05-26 14:28 UTC
Flash icon is not showing.

Its showing F...h in the place of icon. I hope this is a known issue as i can see the change log 0.1.2 mentions its fixed for some devices.

Im facing this problem on iPhone 7 plus with iOS 13.4.1

![WhatsApp Image 2020-05-26 at 7 10 56 PM](https://user-images.githubusercontent.com/12869773/82912813-23e98b00-9f8b-11ea-8735-9a183b66bce9.jpeg)

**Comment by badrussamsi** [comment] 2020-06-27 08:31
i got same issue, in iphone 6. hope this issue will be fix immediately

**Comment by 362228416** [comment] 2020-07-06 15:09
i got same issue, in iphone 6 plus.

**Comment by 362228416** [comment] 2020-07-06 15:11
version: 
flutter_barcode_scanner: ^1.0.1

**Comment by raphaaugustosilva** [comment] 2020-11-17 19:36
Any update about this fix?

**Comment by AmolGangadhare** [comment] 2020-12-19 13:38
This issue has been resolved and will be available in the coming release.

**Comment by AsjadSiddiqui** [comment] 2021-01-04 19:49
@AmolGangadhare Any updates on this?
When will the release be available?

**Comment by AmolGangadhare** [comment] 2021-01-04 20:15
@AsjadSiddiqui It will be available soon

**Comment by AmolGangadhare** [comment] 2021-01-05 21:09
The fix has been made and the new version is available 1.0.2

**Comment by irockel** [comment] 2021-01-15 07:58
I just started using this plugin, using version 1.0.2, but I'm also having this issue. The Icon is not showing on ios.

**Comment by ajbarry** [comment] 2021-01-20 16:05
Likewise, I just upgraded to 1.0.2 hoping it would fix this issue but we're still seeing the truncated `F...h` string instead of a flash icon. Is there another dependency needed? I thought it might need `cupertino_icons` but adding that dependency had no effect.

**Comment by MichaelDark** [comment] 2021-02-11 18:49
> This issue has been resolved and will be available in the coming release.

@AmolGangadhare Could you please check if icons are actually loaded from Bundle? 

Please, check this hints, I think the problem is that this icons never had been loaded:
https://stackoverflow.com/a/35903720
https://stackoverflow.com/a/52504264

**Comment by FahriBilici** [comment] 2021-03-15 15:03
any updates about this problem?

**Comment by andibardhi** [comment] 2021-03-23 08:58
Still showing F...h

**Comment by d11r** [comment] 2021-04-03 20:15
+1, still showing F...h

**Comment by d11r** [comment] 2021-04-03 20:15
Maybe make a fallback to display a string (like you did with Cancel) if icon is unavailable

**Comment by MichaelDark** [comment] 2021-04-05 10:20
> > This issue has been resolved and will be available in the coming release.
> 
> @AmolGangadhare Could you please check if icons are actually loaded from Bundle?
> 
> Please, check this hints, I think the problem is that this icons never had been loaded:
> https://stackoverflow.com/a/35903720
> https://stackoverflow.com/a/52504264

@d11r @AmolGangadhare We need IOS dev, who can deal with bundled resources and who will set up icon. Any ideas?

**Comment by izzyaf** [comment] 2021-04-07 08:50
This should be fixed by this PR: https://github.com/AmolGangadhare/flutter_barcode_scanner/pull/184.

For anyone in need of a temporary solution while waiting for the above PR to be merged, setup `flutter_barcode_scanner` like this in your `pubspec.yaml`:

```yaml
flutter_barcode_scanner:
    git:
      url: git@github.com:izzyaf/flutter_barcode_scanner.git
      ref: master
```

**Closed** 2021-04-19 19:18 UTC
Labels: high-priority, iOS, resolved, under-evaluation
