### ISSUE TITLE
Cooldown time

### ISSUE THREAD

**Issue by eduardotq** [AmolGangadhare/flutter_barcode_scanner#125] opened 2020-10-02 13:38 UTC
Hi, would have some possibility to set a cooldown time in the continuous scan? It's because when I'm using it, sometime it scans too fast and register the same barcode more than one time. If you could set some cooldown time, would be nice. Thank you!

**Comment by nvma** [comment] 2020-10-03 17:55
I've also encountered this problem. You can enforce intervals between scans by transforming the stream, I'm pretty new to reactive programming but it does work as intended. 
```
subscription = FlutterBarcodeScanner.getBarcodeStreamReceiver(
      '#FF0000',
      'CLOSE',
      true,
      ScanMode.BARCODE,
    ).transform(
      StreamTransformer.fromHandlers(
        handleData: (data, sink) {
          if (timer == null) {
            sink.add(data);

            // Set desirable interval in Duration.
            timer = Timer(Duration(seconds: 1), () {
              timer = null;
            });
          }
        },
      ),
    ).listen((barcode) {
      if ((barcode ?? '').isEmpty || barcode == '-1') {
        subscription.cancel();
        return;
      }
     // Do something with barcode
    });
```

**Comment by eduardotq** [comment] 2020-10-03 18:20
I'm a newbie programmer, so I had no ideia how to solve this problem..
Thank you very much!

**Comment by nvma** [comment] 2020-10-16 13:25
Would be a good idea to close the issue if it's resolved for you. Cheers!

**Comment by eduardotq** [comment] 2020-10-16 15:10
Sorry, I forgot

**Closed** 2020-10-16 15:10 UTC
Labels: enhancement

**Comment by alperen23230** [comment] 2020-12-28 11:19
Thank you for solution. It's work very well 👍🏾
