### ISSUE TITLE
Localization of the Cancel button

### ISSUE THREAD

**Issue by kostasoft** [AmolGangadhare/flutter_barcode_scanner#3] opened 2019-03-27 18:18 UTC
How can I localize the Cancel button? 
Thank!

**Comment by AmolGangadhare** [comment] 2019-03-28 07:16
Hi @kostasoft,
I've updated the plugin on the pub. You can use the new version 0.0.7 in which you can pass cancel button text as per your choice. Thanks for your query, you helped to improve the plugin. If you face any issue you can help me to improve plugin by reporting. Also please update on this if possible.
Thanks

**Comment by kostasoft** [comment] 2019-03-28 13:29
Thank you very much!
Can you make the flash button off (invisible)? On my test phone (Android 4.2.2), clicking on this button crashes the application

**Comment by AmolGangadhare** [comment] 2019-03-28 13:32
Can you provide some logs?

**Comment by kostasoft** [comment] 2019-03-29 12:35
```
    --------- beginning of /dev/log/system
03-29 15:35:03.941 32497-32497/com.kostasoft.helpsignalflutter E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.RuntimeException: Fail to connect to camera service
        at android.hardware.Camera.native_setup(Native Method)
        at android.hardware.Camera.<init>(Camera.java:363)
        at android.hardware.Camera.open(Camera.java:321)
        at com.amolg.flutterbarcodescanner.camera.CameraSource.createCamera(CameraSource.java:691)
        at com.amolg.flutterbarcodescanner.camera.CameraSource.start(CameraSource.java:323)
        at com.amolg.flutterbarcodescanner.camera.CameraSourcePreview.startIfReady(CameraSourcePreview.java:92)
        at com.amolg.flutterbarcodescanner.camera.CameraSourcePreview.start(CameraSourcePreview.java:66)
        at com.amolg.flutterbarcodescanner.camera.CameraSourcePreview.start(CameraSourcePreview.java:73)
        at com.amolg.flutterbarcodescanner.BarcodeCaptureActivity.startCameraSource(BarcodeCaptureActivity.java:324)
        at com.amolg.flutterbarcodescanner.BarcodeCaptureActivity.onClick(BarcodeCaptureActivity.java:387)
        at android.view.View.performClick(View.java:4278)
        at android.view.View$PerformClick.run(View.java:17430)
        at android.os.Handler.handleCallback(Handler.java:725)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:5092)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:564)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by AmolGangadhare** [comment] 2019-04-01 11:32
Thanks for the logs, I'm looking into this and it will be fixed in next release. I'll also add a flag for flash, by which users can now show or hide the flash icon.

**Comment by kostasoft** [comment] 2019-04-01 13:21
Thank you very much!

**Comment by AmolGangadhare** [comment] 2019-04-12 13:44
I've updated the plugin and is published on the pub. I was not able to reproduce the issue you're getting, but still, I'm checking for this. I found a potential issue and fixed that. Please try this and revert if you face any issue.

**Comment by AmolGangadhare** [comment] 2019-07-10 06:37
This has been done. But the error was not reproducible. So closing this.

**Closed by AmolGangadhare** 2019-07-10 06:37 UTC
Labels: enhancement
