### ISSUE TITLE
Camera overlay

### ISSUE THREAD

**Issue by Mythar** [AmolGangadhare/flutter_barcode_scanner#14] opened 2019-06-03 07:45 UTC
Hello, nice scanner :)
It would be nice to have both a qr code and barcode camera overlay.
It works the same will just look better on the screen.
Square overlay for qr (as you have now) and rectangular overlay for barcodes.

Eks: String barcodeScanRes = await FlutterBarcodeScanner.scanBarcode(SCAN_MODE,COLOR_CODE,CANCEL_BUTTON_TEXT,isShowFlashIcon);

**Comment by AmolGangadhare** [comment] 2019-06-03 08:49
Hi,

Thanks for using the plugin. It is a good idea to have different overlays for QR and barcode. I will be experimenting with different overlays. Will update you on this whenever it will be working.

**Comment by Mythar** [comment] 2019-06-09 10:42
Sounds good :)
Btw: You sould add "s.swift_version = '?.?'" to your .podspec file ;)

**Comment by AmolGangadhare** [comment] 2019-09-25 13:42
@Mythar 
This is implemented in V 0.1.7 release. 

If possible can you try it out and acknowledge?

Thanks

**Comment by Mythar** [comment] 2019-09-28 11:31
Hello @AmolGangadhare, I have not had the time to check it out - sry.

Im currently using another barcode reader.
To go back to ur's (and i would like to very mush).
The following issues mush be handled:

1st AND most important: ability to chose the barcode formats.
- Most of the products scanned has a QR code right next to the barcode, so can't have a scanner that sometimes scan barcode and sometimes scan the QR code.

2nd MUST support low end phones; i cant demand of my customers to go out and buy new phones.

3th EASY way to setup one time scans and multiply scans; need: pause, resume, stop.
- ei. as another wrote; scan -> enter quantity and other order data, scan next etc. (w/o closing the camera as this will slow down scanning, if ur scanning say 100-1000 products.

**Comment by AmolGangadhare** [comment] 2019-10-01 11:16
@Mythar 

Most of the suggestions are already available in the plugin.
* The continuous scan feature is already available in the plugin. 
* The overlay is just a graphical representation. Any of them selected will scan both QR and Barcode.
* For support to low-end devices, can you give some devices/ model name you tried on?

**Comment by Mythar** [comment] 2019-10-12 05:56
1st and formost i need to be able to set the barcode format, i can not use your plugin until this is done.

**Comment by Mythar** [comment] 2019-10-14 11:54
I have an old Galaxy J5 to test on, and scanner dose not work on it.
I suspect resolution is too low

**Comment by AmolGangadhare** [comment] 2019-11-26 10:10
@Mythar 

We use Google Vision API for android. This API is available with Play services which might be unstable with low-end devices (As I was not able to reproduce this issue on every device I have). I'll still update you if there is any progress about this issue you are facing.

Anyways the vision API is now deprecated and I'm planning to integrate ML Kit in this plugin soon which might solve these related issues.

As the issue is about camera overlay and which is implemented in the current version, this issue is resolved. So closing this one. Please do not hesitate to reopen this issue if you face any issues related to camera overlay.

Thanks

**Closed by AmolGangadhare** 2019-11-26 10:10 UTC
Labels: enhancement, resolved
