### ISSUE TITLE
Cancel button event listener

### ISSUE THREAD

**Issue by ZayLong** [AmolGangadhare/flutter_barcode_scanner#26] opened 2019-08-03 20:22 UTC
is there a way to listen for when the user presses the cancel button?

When using the barcode scanner with a BLoC pattern, i'm firing an event to trigger the barcode scanner to run, but is there some event i can listen for when it cancels so I can reset the state?

**Comment by AmolGangadhare** [comment] 2019-08-06 06:14
Duplicate #8

**Comment by ZayLong** [comment] 2019-08-08 19:05
How is this a duplicate? The thread you linked doesn't show how to make a listener for canceling the barcode scan.


I need to be able to execute a piece of code when that cancel button is pressed/

**Comment by AmolGangadhare** [comment] 2019-08-09 04:52
@ZayLong Plugin does not have cancel button event listener functionality at this moment.
This issue is duplicate of #8 as both issues require the same functionality. Rather than keeping both issues, every possible solution or workaround can be put in a single thread for ease of use. There is a workaround in linked issue to decide the cancel button event.

**Comment by annagat** [comment] 2020-01-29 09:02
Below is my workaround on this issue.

```
 void scanBarcode() async {
    allowCamera();
    String barcode = await FlutterBarcodeScanner.scanBarcode("#ff6666", "Cancel", true, ScanMode.DEFAULT);
    setState(() {
      if (barcode.length > 0) {
        _barcodeString = barcode;
        _showForm = true;
      } else {
        _barcodeString = '';
      }  
    });

    // Don't show form if barcode sacnner is cancelled
    if (barcode == "-1") {
      _showForm = false;
    }
  }
```

**Comment by AmolGangadhare** [comment] 2020-04-30 20:35
Closing this as the original issue has a workaround to implement this.

Please refer to #8

**Closed by AmolGangadhare** 2020-04-30 20:35 UTC
Labels: duplicate, enhancement
