### ISSUE TITLE
compatibilidade com flutter 2.7

### ISSUE THREAD

**Issue by DiegoLimeiradaSilva** [AmolGangadhare/flutter_barcode_scanner#59] opened 2019-12-12 17:54 UTC
I tried to compile the crash app on opening. if I try to take the project's dependency works normal

**Comment by kientux** [comment] 2019-12-13 08:25
Latest version of Flutter use `io.flutter.embedding.android.FlutterActivity` instead of `io.flutter.app.FlutterActivity`. But this library casts the activity to latter one so app crashes:

```java
instance = new FlutterBarcodeScannerPlugin((FlutterActivity) registrar.activity(), registrar);
```

You must wait for the author to update this lib or fork and use your own version.

**Comment by AmolGangadhare** [comment] 2019-12-13 09:41
@DiegoLimeiradaSilva 
Thanks for reporting the issue.

I'm not able to reproduce this issue.
Can you add some error logs? It will help me to reproduce the issue.

**Comment by DiegoLimeiradaSilva** [comment] 2019-12-13 11:02
I already downgraded the version of flutter .. I will try to simulate again .. but I remember simply gave no error in VSCODE just finished the app

**Comment by DiegoLimeiradaSilva** [comment] 2019-12-13 11:40
Could not update files on device: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:57092/cUTgIgYNPA4=/

this is the mistake that gives in debug console

**Comment by DiegoLimeiradaSilva** [comment] 2019-12-13 11:57
@kientux tks.

@AmolGangadhare 
i changing my cache FlutterBarcodeScannerPlugin.java

new import io.flutter.embedding.android.FlutterActivity

old io.flutter.app.FlutterActivity

https://prnt.sc/qabin6

**Comment by AmolGangadhare** [comment] 2019-12-13 12:04
Is it specific to iOS or Android or on both?

**Comment by DiegoLimeiradaSilva** [comment] 2019-12-13 12:06
for me it's android .. i don't have a mac to compile for ios

**Comment by AmolGangadhare** [comment] 2019-12-13 12:09
Ok, thanks for the information. I'll be releasing a new version soon. It will be resolved in the upcoming release.

**Comment by AmolGangadhare** [comment] 2019-12-18 05:07
@DiegoLimeiradaSilva 

I've made a fix to this but many users are continuously reporting same issue for most of the plugins. 
As of now i think we should wait till official hotfix to this/ any announcement.

To make it run it would be better to downgrade the flutter version.

Don't worry I'll keep you updated on this.

Thanks

**Comment by fiaschi** [comment] 2019-12-21 13:47
import io.flutter.embedding.android.FlutterActivity; resolve for me!

**Comment by AmolGangadhare** [comment] 2019-12-24 13:24
This issue has been resolved. It will be available in the new release.

**Comment by uplinkcreativestudio** [comment] 2020-01-17 02:38
> I already downgraded the version of flutter .. I will try to simulate again .. but I remember simply gave no error in VSCODE just finished the app

my I know, which flutter version when downgrade? it's happen to me too.

**Comment by uplinkcreativestudio** [comment] 2020-01-17 02:38
> for me it's android .. i don't have a mac to compile for ios

ios run well, just in android.

**Comment by uplinkcreativestudio** [comment] 2020-01-17 02:41
> import io.flutter.embedding.android.FlutterActivity; resolve for me!

which flutter version do you use?

**Comment by AmolGangadhare** [comment] 2020-04-30 20:22
V1.0.0 has been released

Closing this, feel free to reopen if the issue persists

**Closed by AmolGangadhare** 2020-04-30 20:22 UTC
Labels: Android, iOS, resolved

**Comment by kapilb145** [comment] 2020-09-17 19:22
replace this

     io.flutter.app.FlutterActivity

with this

     import io.flutter.embedding.android.FlutterActivity
