### ISSUE TITLE
Unhandled Exception: MissingPluginException

### ISSUE THREAD

**Issue by MagicalWater** [AmolGangadhare/flutter_barcode_scanner#7] opened 2019-04-17 07:58 UTC
my code

```
Future scan() async {
    String res = await FlutterBarcodeScanner.scanBarcode("00ccbb", "Cancel", true);
    print("qr scan ${res}");
}
```

and report error 

```
Unhandled Exception: MissingPluginException(No implementation found for method scanBarcode on channel flutter_barcode_scanner)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
```

**Comment by AmolGangadhare** [comment] 2019-04-17 08:40
Hi,
I'll need some information. 
1-> Please confirm are you using it from pub or by cloning it (If using from pub, do you get any errors while `Packages get` in `pubspec.yaml`).
Usually, this error occurs due to errors in `Packages get`.


Also the color code you are passing try adding `#00ccbb` instead of `00ccbb` and check.

**Comment by AlanCZ** [comment] 2019-06-25 10:13
hello, I also encountered the same problem
it occurs when you return from the app and return again

**Comment by AlanCZ** [comment] 2019-06-25 10:13
hello, I also encountered the same problem
it occurs when you return from the app and return again

**Comment by AmolGangadhare** [comment] 2019-07-10 06:43
@AlanCZ I was not able to reproduce this. Can you add some more logs and steps to reproduce this? Is this occurred on Android or in iOS or in both?

**Comment by AmolGangadhare** [comment] 2019-08-07 05:51
@MagicalWater @AlanCZ @fikurniawan @NewComerBH @MatteoColombo
This error seems to occur frequently for many users. I request to please perform some preliminary actions.

1. If you are using Android Studio just try `Invalidate cache and Restart once` meanwhile uninstall the existing installed app from the phone.
2. open cmd/ terminal goto project and do `flutter clean`
3. Go to pubspec and add the latest version of the plugin which is `0.1.5` and click pub packages get.
4. Run project.

I request to please acknowledge that the issue been resolved or not for you.

Thanks

**Comment by MatteoColombo** [comment] 2019-08-07 14:10
@AmolGangadhare 
I had already tried with version `0.1.5` and after `flutter clean`, but it's still happening.
Here is another log:

> 08-07 16:02:42.927 24298  9953 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method scanBarcode on channel flutter_barcode_scanner)
08-07 16:02:42.927 24298  9953 E flutter : #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314)
08-07 16:02:42.927 24298  9953 E flutter : \<asynchronous suspension\>
08-07 16:02:42.927 24298  9953 E flutter : #1      FlutterBarcodeScanner.scanBarcode (package:flutter_barcode_scanner/flutter_barcode_scanner.dart:34)
08-07 16:02:42.927 24298  9953 E flutter : \<asynchronous suspension\>
08-07 16:02:42.927 24298  9953 E flutter : #2      AddBookFloat._addBook (package:dima2018_colombo_troianiello/view/library-page/add-book-float.dart:22)
08-07 16:02:42.927 24298  9953 E flutter : \<asynchronous suspension\>
08-07 16:02:42.927 24298  9953 E flutter : #3      AddBookFloat.build.\<anonymous closure\> (package:dima2018_colombo_troianiello/view/library-page/add-book-float.dart:16)
08-07 16:02:42.927 24298  9953 E flutter : #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635)
08-07 16:02:42.927 24298  9953 E flutter : #5      _InkResponseState.build.\<anonymous closure\> (package:flutter/src/material/ink_well.dart:711)
08-07 16:02:42.927 24298  9953 E flutter : #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182)
08-07 16:02:42.927 24298  9953 E flutter : #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365)
08-07 16:02:42.927 24298  9953 E flutter : #8      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275)
08-07 16:02:42.927 24298  9953 E flutter : #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455)
08-07 16:02:42.927 24298  9953 E flutter : #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75)
08-07 16:02:42.927 24298  9953 E flutter : #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102)
08-07 16:02:42.927 24298  9953 E flutter : #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218)
08-07 16:02:42.927 24298  9953 E flutter : #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198)
08-07 16:02:42.927 24298  9953 E flutter : #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156)
08-07 16:02:42.927 24298  9953 E flutter : #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102)
08-07 16:02:42.927 24298  9953 E flutter : #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86)
08-07 16:02:42.927 24298  9953 E flutter : #17     _rootRunUnary (dart:async/zone.dart:1136)
08-07 16:02:42.927 24298  9953 E flutter : #18     _CustomZone.runUnary (dart:async/zone.dart:1029)
08-07 16:02:42.927 24298  9953 E flutter : #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931)
08-07 16:02:42.927 24298  9953 E flutter : #20     _invoke1 (dart:ui/hooks.dart:250)
08-07 16:02:42.927 24298  9953 E flutter : #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:159)
08-07 16:02:42.927 24298  9953 E flutter : 
08-07 16:02:42.945 24298  9954 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
08-07 16:02:42.932 24298 24298 W 4.gpu   : type=1400 audit(0.0:40701): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=21701 scontext=u:r:untrusted_app:s0:c230,c256,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
08-07 16:02:42.942 24298 24298 W 4.gpu   : type=1400 audit(0.0:40702): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=21701 scontext=u:r:untrusted_app:s0:c230,c256,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
08-07 16:02:42.957 24298  9954 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"

**Comment by AmolGangadhare** [comment] 2019-08-09 06:51
Hi,

I've added a potential fix to this issue with release `0.1.5+1`. I need help from you guys. I request you to check it out with the new version and acknowledge if possible.

**Comment by MatteoColombo** [comment] 2019-08-12 08:18
Hi, it seems that the bug is solved. I'll let you know if it will happen again.
Thank you!

**Comment by AmolGangadhare** [comment] 2019-08-12 08:31
@MatteoColombo Thanks for checking. If you face any issue please feel free to report.

**Comment by AmolGangadhare** [comment] 2019-08-28 09:19
Closing this as it seems to be resolved.

**Closed by AmolGangadhare** 2019-08-28 09:19 UTC
Labels: bug, resolved

**Comment by mariolouisvincent** [comment] 2020-07-29 15:10
@AmolGangadhare I have encountered an error regarding an issue @MatteoColombo had and I have tried the fixes you suggested which are: 

- used latest version
- invalidate cache and restart
- flutter clear
- hard reset application

Case:
I am building an App where I scan a barcode and if code matches mobile device may access administrative permissions to device. I am having an issue when I communicate with the MainActivity.java in my project which also has a MethodCall. Could that be a conflict to the MethodCall in the plugin?

Error:
E/flutter (27900): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method scanBarcode on channel flutter_barcode_scanner)
E/flutter (27900): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (27900): <asynchronous suspension>
E/flutter (27900): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (27900): #2      FlutterBarcodeScanner.scanBarcode (package:flutter_barcode_scanner/flutter_barcode_scanner.dart:42:43)
E/flutter (27900): #3      _ScanQRControllerState.scanQRCode2 (package:FlutterApp/Controllers/ScanQRController.dart:112:47)
E/flutter (27900): #4      _ScanQRControllerState.build.<anonymous closure> (package:FlutterApp/Controllers/ScanQRController.dart:64:32)
E/flutter (27900): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
E/flutter (27900): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter (27900): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (27900): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter (27900): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter (27900): #10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
E/flutter (27900): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter (27900): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (27900): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (27900): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (27900): #15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (27900): #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (27900): #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (27900): #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (27900): #19     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (27900): #20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (27900): #21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (27900): #22     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter (27900): #23     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (27900): #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (27900): #25     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter (27900): #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)

**Comment by jayclockwork** [comment] 2020-10-20 16:27
I am experiencing the same exception. I am using version 1.0.1. I have tried `flutter clean`.

My code for using the scanner is:

```
  Future<void> scanBarcode() async {
    final scanResult = await scanner.scan();
    print(scanResult);
```

The text of the exception is:

```
Exception has occurred.
MissingPluginException (MissingPluginException(No implementation found for method scan on channel qr_scan))
```

```
MethodChannel._invokeMethod (/Users/jayhaase/flutter/packages/flutter/lib/src/services/platform_channel.dart:157)
<asynchronous gap> (Unknown Source:0)
MethodChannel.invokeMethod (/Users/jayhaase/flutter/packages/flutter/lib/src/services/platform_channel.dart:332)
scan (/Users/jayhaase/flutter/.pub-cache/hosted/pub.dartlang.org/qrscan-0.2.17/lib/qrscan.dart:13)
_ScannerState.scanBarcode (/Users/jayhaase/Desktop/flutter/optum-flm-app/lib/screens/retail_scanner/components/scanner.dart:16)
_ScannerState.scanBarcode (/Users/jayhaase/Desktop/flutter/optum-flm-app/lib/screens/retail_scanner/components/scanner.dart:0)
_InkResponseState._handleTap (/Users/jayhaase/flutter/packages/flutter/lib/src/material/ink_well.dart:993)
_InkResponseState.build.<anonymous closure> (/Users/jayhaase/flutter/packages/flutter/lib/src/material/ink_well.dart:1111)
GestureRecognizer.invokeCallback (/Users/jayhaase/flutter/packages/flutter/lib/src/gestures/recognizer.dart:183)
TapGestureRecognizer.handleTapUp (/Users/jayhaase/flutter/packages/flutter/lib/src/gestures/tap.dart:598)
BaseTapGestureRecognizer._checkUp (/Users/jayhaase/flutter/packages/flutter/lib/src/gestures/tap.dart:287)
BaseTapGestureRecognizer.handlePrimaryPointer (/Users/jayhaase/flutter/packages/flutter/lib/src/gestures/tap.dart:222)
PrimaryPointerGestureRecognizer.handleEvent (/Users/jayhaase/flutter/packages/flutter/lib/src/gestures/recognizer.dart:476)
PrimaryPointerGestureRecognizer.handleEvent (/Users/jayhaase/flutter/packages/flutter/lib/src/gestures/recognizer.dart:0)
PointerRouter._dispatch (/Users/jayhaase/flutter/packages/flutter/lib/src/gestures/pointer_router.dart:77)
PointerRouter._dispatchEventToRoutes.<anonymous closure> (/Users/jayhaase/flutter/packages/flutter/lib/src/gestures/pointer_router.dart:122)
_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377)
PointerRouter._dispatchEventToRoutes (/Users/jayhaase/flutter/packages/flutter/lib/src/gestures/pointer_router.dart:120)
PointerRouter.route (/Users/jayhaase/flutter/packages/flutter/lib/src/gestures/pointer_router.dart:106)
GestureBinding.handleEvent (/Users/jayhaase/flutter/packages/flutter/lib/src/gestures/binding.dart:358)
GestureBinding.dispatchEvent (/Users/jayhaase/flutter/packages/flutter/lib/src/gestures/binding.dart:338)
RendererBinding.dispatchEvent (/Users/jayhaase/flutter/packages/flutter/lib/src/rendering/binding.dart:267)
GestureBinding._handlePointerEvent (/Users/jayhaase/flutter/packages/flutter/lib/src/gestures/binding.dart:295)
GestureBinding._flushPointerEventQueue (/Users/jayhaase/flutter/packages/flutter/lib/src/gestures/binding.dart:240)
GestureBinding._handlePointerDataPacket (/Users/jayhaase/flutter/packages/flutter/lib/src/gestures/binding.dart:213)
GestureBinding._handlePointerDataPacket (/Users/jayhaase/flutter/packages/flutter/lib/src/gestures/binding.dart:0)
_rootRunUnary (dart:async/zone.dart:1206)
_rootRunUnary (dart:async/zone.dart:0)
_CustomZone.runUnary (dart:async/zone.dart:1100)
_CustomZone.runUnaryGuarded (dart:async/zone.dart:1005)
_invoke1 (dart:ui/hooks.dart:265)
_dispatchPointerDataPacket (dart:ui/hooks.dart:174)
```
