### ISSUE TITLE
Flutter v1.12.13+hotfix.5, bug on compile

### ISSUE THREAD

**Issue by LuizLeite** [AmolGangadhare/flutter_barcode_scanner#60] opened 2019-12-12 19:05 UTC
Hi.

This package ran very well, but in the new version of Flutter,
it has been a problem compiling and running.

Flutter v1.12.13+hotfix.5
Dart 2.7.0

Tanks

**Comment by AmolGangadhare** [comment] 2019-12-13 09:43
@LuizLeite 

Thanks for reporting the issue.

I'm not able to reproduce this issue.
Can you add some error logs or some steps to reproduce this?

**Comment by LuizLeite** [comment] 2019-12-13 18:32
Hi.
1) Create a default Flutter 1.12.13 project.
2) Install the package.
3) When running a dialog appears on the Android screen saying that my app has stopped.
Only that.

**Comment by AmolGangadhare** [comment] 2019-12-18 05:06
@LuizLeite 

I've made a fix to this but many users are continuously reporting same issue for most of the plugins. 
As of now i think we should wait till official hotfix to this/ any announcement.

To make it run it would be better to downgrade the flutter version.

I'll keep you updated on this.

Thanks

**Comment by marcos930807** [comment] 2019-12-18 20:17
> Hi.
> 
> 1. Create a default Flutter 1.12.13 project.
> 2. Install the package ^0.1.7.
> 3. When running a dialog appears on the Android screen saying that my app has stopped.
> 4. if I remove the package the app runs normally.
>    Only that.

Same happens to me

**Comment by varunnayal** [comment] 2019-12-23 07:36
@LuizLeite @marcos930807: You can try using solution mentioned in [this](https://github.com/flutter/flutter/issues/27254#issuecomment-458689343) and [this](https://github.com/flutter/flutter/issues/27254#issuecomment-477474444) comment. It worked for me!

**Comment by marcos930807** [comment] 2019-12-23 19:23
In my case i modified my cache pup project and cast to a FlutterFragmentActivity because that is the entry Point of my Android part. Thanks

**Comment by AmolGangadhare** [comment] 2019-12-24 13:23
This issue has been resolved. It will be available in the new release.

**Comment by kumarmohan7** [comment] 2019-12-25 18:52
please release this issue solution.

**Comment by nandychu** [comment] 2019-12-26 11:48
Same problem, can you give a solution or release the new fixed version? thanks!

**Comment by HektorCyC** [comment] 2019-12-29 01:10
Is this resolved in a new release? Which version??

**Comment by nandychu** [comment] 2019-12-29 18:16
Seems that its fixed on last commit, not available on pub yet btw, installed via git, on pubspec paste:
`  flutter_barcode_scanner: 
    git: git://github.com/AmolGangadhare/flutter_barcode_scanner.git
`

**Comment by HosseinTraining** [comment] 2019-12-29 18:25
I have this problem too
please release updated about this issue

**Comment by HektorCyC** [comment] 2019-12-31 00:05
> Seems that its fixed on last commit, not available on pub yet btw, installed via git, on pubspec paste (take care of indentation):
> ` flutter_barcode_scanner: git: git://github.com/AmolGangadhare/flutter_barcode_scanner.git`

Here's the right way to install from Git
https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages

**Comment by uplinkcreativestudio** [comment] 2020-01-17 07:52
run well when changing my cache FlutterBarcodeScannerPlugin.java

new import io.flutter.embedding.android.FlutterActivity

old io.flutter.app.FlutterActivity

https://prnt.sc/qabin6

**Comment by cshummod** [comment] 2020-01-20 14:13
I installed it from pub.dev but without any luck.

FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleAarRelease' not found in root project 'flutter_barcode_scanner'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.      

* Get more help at https://help.gradle.org

BUILD FAILED in 0s


The plugin flutter_barcode_scanner could not be built due to the issue above.

**Comment by Elvino12** [comment] 2020-02-18 12:36
I had the same issues, and i solved change the mod that i import the package on pubspec.yam
like this: 
flutter_barcode_scanner:
    git: git://github.com/AmolGangadhare/flutter_barcode_scanner.git

**Comment by AmolGangadhare** [comment] 2020-04-30 20:22
V1.0.0 has been released

Closing this, feel free to reopen if the issue persists

**Closed by AmolGangadhare** 2020-04-30 20:22 UTC
Labels: Android, iOS, resolved
