### ISSUE TITLE
Crash on Android

### ISSUE THREAD

**Issue by vkusenko** [AmolGangadhare/flutter_barcode_scanner#47] opened 2019-10-31 11:55 UTC
Caused by java.lang.NullPointerException
Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
com.amolg.flutterbarcodescanner.FlutterBarcodeScannerPlugin.onActivityResult

- Device: Pixel 1
- OS: android 10
- Version plugin: ^0.1.7

**Comment by AmolGangadhare** [comment] 2019-11-11 13:23
@vkusenko Try to bump up flutter app android `compileSdkVersion` and `targetSdkVersion` to 29 which is Android 10 and run the app.

**Comment by zulandar** [comment] 2019-11-18 00:04
I ran a bare min example and it worked successfully for me.

```
minSdkVersion 16
targetSdkVersion 28
```

- Emulator: Pixel 3a XL API 29
- Android: 10
- Plugin: ^0.1.7

**Comment by wurstnudl** [comment] 2020-01-14 14:32
Nope, it doesn't work when pressing the "Cancel" button.

I assume the reason is that the field "pendingResult" is never actually set when cancelling (this would happen in "onMethodCall"), "onActivityResult" is being called and "pendingResult" is null.

**Comment by wurstnudl** [comment] 2020-01-16 12:28
Nope, sorry, scanning also fails with a nullpointer at 

`Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference 	at com.amolg.flutterbarcodescanner.FlutterBarcodeScannerPlugin.onActivityResult(FlutterBarcodeScannerPlugin.java:157)
`

I'm using a github reference in the pubspec because otherwise, the app crashes on start up. See other related issues.

I'm running an Android 10.
FlutterVersion = v1.12.13+hotfix.6

**Comment by AmolGangadhare** [comment] 2020-01-16 12:44
@wurstnudl 

Thanks for the details.

I am not able to reproduce this issue. But In flutter v1.12.13 there is a migration to new APIs is required.
I've made the migration(which is a major change) and it will be available with the new release. 
I think let's try it in new version which is coming soon and see if this issue persists.

Thanks

**Comment by AmolGangadhare** [comment] 2020-04-30 20:40
V1.0.0 has been released

closing this, please feel free to reopen this if the issue persists

**Closed by AmolGangadhare** 2020-04-30 20:40 UTC
Labels: awaiting-response

**Comment by AhmedTawfiqM** [comment] 2023-09-14 22:48
Had u find a solution to this issue ?
