### ISSUE TITLE
Does plugin require NSPhotoLibraryUsage ?

### ISSUE THREAD

**Issue by pamir72** [AmolGangadhare/flutter_barcode_scanner#36] opened 2019-09-25 15:52 UTC
When I uploaded my app into AppStore I got the refusal with warning NSPhotoLibraryUsageDescription is absent. Does plugin require NSPhotoLibraryUsage ?

**Comment by AmolGangadhare** [comment] 2019-09-25 19:17
@pamir72 
The plugin doesn't require **NSPhotoLibraryUsageDescription**. 
Only **NSCameraUsageDescription** is required here.

Can you provide a complete warning?

Thanks

**Comment by pamir72** [comment] 2019-09-25 19:21
ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSPhotoLibraryUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more 
----
It is strange, but the warning appeared after plug-in connected

**Comment by AmolGangadhare** [comment] 2019-09-25 19:30
It's strange. Possible reasons for this
1. Used **NSPhotoLibraryUsageDescription** in code but not added in info.plist
2. Added in plist but the description is unclear or not sufficient.

Can you provide your plist file and the pubspec file (If possible)?
After that, we can figure it out.

**Comment by pamir72** [comment] 2019-09-25 19:36
I didn't have NSPhotoLibraryUsageDescription in the info.plist and the code
After rejecting, I added a description into info.plist and uploaded app successfully

**Comment by pamir72** [comment] 2019-09-25 19:42
pabspec:


environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_webview_plugin: ^0.3.8
  cupertino_icons: ^0.1.2
  firebase_messaging: ^5.1.6
  flutter_barcode_scanner: ^0.1.6
  provider: ^3.1.0

**Comment by AmolGangadhare** [comment] 2019-10-06 18:22
@pamir72 
Did the issue is resolved?
I have gone through it several times and I was able to make it work without **NSPhotoLibraryUsageDescription**.

**Comment by pamir72** [comment] 2019-10-06 18:30
I've set NSPhotoLibrariUsageDescription as Apple recommended and then never returned to this question.

**Comment by AmolGangadhare** [comment] 2019-10-06 18:37
Did the app was deployed successfully after adding the permission?

**Comment by pamir72** [comment] 2019-10-06 18:38
Yes

**Comment by AmolGangadhare** [comment] 2019-10-06 18:40
Ok, thanks for the confirmation. Unfortunately, you faced this issue. 
I'm marking this issue as resolved.

**Comment by AmolGangadhare** [comment] 2019-11-11 12:28
Closing this issue as it is resolved

**Closed by AmolGangadhare** 2019-11-11 12:28 UTC
Labels: app-deployment, resolved
