### ISSUE TITLE
example does not open when build apk

### ISSUE THREAD

**Issue by Tucho-Will** [AmolGangadhare/flutter_barcode_scanner#63] opened 2020-01-06 14:40 UTC
Generating the apk doesn't open the app I used the latest version of the repository.
I'm using android 9.

StackTrace
```
Process: com.amolg.flutterbarcodescannerexample, PID: 27358
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amolg.flutterbarcodescannerexample/io.flutter.embedding.android.FlutterActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.lifecycle.f.a(androidx.lifecycle.h)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.lifecycle.f.a(androidx.lifecycle.h)' on a null object reference
        at com.amolg.flutterbarcodescanner.FlutterBarcodeScannerPlugin.a(Unknown Source:73)
        at com.amolg.flutterbarcodescanner.FlutterBarcodeScannerPlugin.a(Unknown Source:27)
        at io.flutter.embedding.engine.c.a(Unknown Source:106)
        at io.flutter.embedding.android.d.a(Unknown Source:57)
        at io.flutter.embedding.android.FlutterActivity.onCreate(Unknown Source:22)
        at android.app.Activity.performCreate(Activity.java:7458)
        at android.app.Activity.performCreate(Activity.java:7448)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
```

**Comment by AmolGangadhare** [comment] 2020-01-14 05:40
Duplicate of #60

**Comment by AmolGangadhare** [comment] 2020-04-30 20:16
V1.0.0 has been released

This issue is supposed to resolve.

Closing this as of now please feel free to reopen if the issue persists

**Closed by AmolGangadhare** 2020-04-30 20:16 UTC
Labels: duplicate
